name: GISAID fetch and ingest (on branch)

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '**'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: setup
      run: ./bin/setup-github-workflow

    - name: ingest
      run: |
        ./bin/write-envdir env.d \
          AWS_DEFAULT_REGION \
          GISAID_API_ENDPOINT \
          GISAID_USERNAME_AND_PASSWORD \
          GITHUB_REF \
          SLACK_TOKEN

        nextstrain build \
          --aws-batch \
          --no-download \
          --image nextstrain/ncov-ingest \
          --cpus 8 \
          --memory 15GiB \
          --exec env \
          . \
            envdir env.d snakemake gisaid_then_clean \
              --config fetch="yes" slack_token='${{ secrets.SLACK_TOKEN }}' \
                       gisaid_login='${{ secrets.GISAID_USERNAME_AND_PASSWORD }}' \
                       gisaid_endpoint='${{ secrets.GISAID_API_ENDPOINT }}'
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GISAID_API_ENDPOINT: ${{ secrets.GISAID_API_ENDPOINT }}
        GISAID_USERNAME_AND_PASSWORD: ${{ secrets.GISAID_USERNAME_AND_PASSWORD }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
