name: GenBank ingest

on:
  # Manually triggered using `./vendored/trigger nextstrain/ncov-ingest genbank/ingest` (or `ingest`, which
  # includes GISAID)
  repository_dispatch:
    types:
      - genbank/ingest
      - ingest

  # Manually triggered using GitHub's UI
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
      SLACK_CHANNELS: ncov-genbank-updates
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: nextstrain/.github/actions/setup-nextstrain-cli@master

    - name: run_pipeline
      run: |
        ./bin/write-envdir env.d \
          AWS_DEFAULT_REGION \
          SLACK_TOKEN \
          GITHUB_RUN_ID \
          SLACK_CHANNELS

        nextstrain build \
          --aws-batch \
          --detach \
          --no-download \
          --image nextstrain/ncov-ingest \
          --cpus 16 \
          --memory 68GiB \
          --exec env \
          . \
            envdir env.d snakemake \
              --configfile config/genbank.yaml \
              --cores 16 \
              --resources mem_mb=68000 \
              --printshellcmds
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: notify_pipeline_failed
      if: ${{ failure() }}
      run: ./vendored/notify-on-job-fail Ingest nextstrain/ncov-ingest
