name: GenBank ingest

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # "At 03:00 (05:00 CET, 20:00 PDT the previous day) every Tuesday."
    - cron:  '0 3 * * TUE'

  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths:
      - source-data/genbank_annotations.tsv

  # Manually triggered using `./bin/trigger genbank/ingest` (or `ingest`, which
  # includes GISAID)
  repository_dispatch:
    types:
      - genbank/ingest
      - ingest

  # Manually triggered using GitHub's UI
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: setup
      run: ./bin/setup-github-workflow

    - name: ingest
      run: |
        ./bin/write-envdir env.d \
          AWS_DEFAULT_REGION \
          GITHUB_REF \
          SLACK_TOKEN

        nextstrain build \
          --aws-batch \
          --no-download \
          --image nextstrain/ncov-ingest \
          --cpus 16 \
          --memory 30GiB \
          --exec env \
          . \
            envdir env.d snakemake genbank_then_clean -j 16 \
               --config fetch="yes" slack_token='${{ secrets.SLACK_TOKEN }}'
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}